polychrome: $(SAPI_POLYCHROME_PATH)

$(SAPI_POLYCHROME_PATH): $(PHP_GLOBAL_OBJS) $(PHP_BINARY_OBJS) $(PHP_POLYCHROME_OBJS) $(POLYCHROME_RUST_LIB)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -export-dynamic $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(EXTRA_LDFLAGS_PROGRAM) $(LDFLAGS) $(PHP_RPATHS) $(PHP_GLOBAL_OBJS:.lo=.o) $(PHP_BINARY_OBJS:.lo=.o) $(PHP_POLYCHROME_OBJS:.lo=.o) $(POLYCHROME_RUST_LIB) $(EXTRA_LIBS) $(ZEND_EXTRA_LIBS) -lpthread -ldl -lm -o $(SAPI_POLYCHROME_PATH)

install-polychrome: $(SAPI_POLYCHROME_PATH)
	@$(mkinstalldirs) $(INSTALL_ROOT)$(bindir)
	@$(LIBTOOL) --mode=install $(INSTALL) -m 0755 $(SAPI_POLYCHROME_PATH) $(INSTALL_ROOT)$(bindir)/polychrome
